# eureka:
#     client:
#         serviceUrl:
#             defaultZone: http://localhost:8083/eureka
# spring:
#     boot:
#       admin:
#          client:
#               url: http://localhost:8093   
# management:
#     endpoint:
#         health:
#             show-details: always
#     endpoints:
#         web:
#             exposure:
#                 include: "*"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
logging:
    pattern:
#         console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n"
        level  : "%d{ABSOLUTE} [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n"
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/api/v1/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/api/v1/order/bookOrder     
              
