eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8083/eureka
spring:
    boot:
      admin:
         client:
              url: http://localhost:8093   
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"
              
